// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"database/sql"
)

type Post struct {
	ID        int32
	Title     string
	Content   sql.NullString
	UserID    sql.NullInt32
	CreatedAt sql.NullTime
}

type User struct {
	ID        int32
	Username  string
	Email     string
	CreatedAt sql.NullTime
}
